### ISSUE TITLE
Convos tries to look for "future" channel logs causing an infinite loop

### ISSUE THREAD

**Issue by serhack** [Nordaaker/convos#459] opened 2020-04-26 20:05 UTC
I installed Convos 5 months ago and I've collected so many messages and channels since that period. From time to time, my server suffered some "downs" and I thought it was a temporary problem caused by some local conflicts with other programs that bind the same network interface. However as the number of the messages logged was increasing, my suffered more downs than ever. At the moment, each time I want to access to IRC via Convos, I have to restart Convos via terminal. It's a little bit annoying.

When I write "down", I mean the situation of not-accessing the convos interface. Instead the "Convos is offline" warning is showed.
I might assume all of this since in particular the API call `/api/user.json?connections=true&dialogs=true` fails returning a time-out code. I'm suspecting that the search component request too many files (~~90 days of "full activity" in channels are like looking for a string in 500k lines~~ maybe does it look for future logs?) to servers.

### Technical information
* OS: Debian 10 64bit;
* Convos version: 4.03;
* Browser: Chromium-based;

**Comment by serhack** [comment] 2020-04-26 20:12
No relevant log is showed in `STDERR` using `CONVOS_DEBUG=1`.

**Comment by jhthorsen** [comment] 2020-04-26 20:22
Could it be an `ulimit` issue? Can you see anything interesting in your syslog?

**Comment by jhthorsen** [comment] 2020-04-26 21:38
Could it be an `ulimit` issue? Can you see anything interesting in your syslog? What about file permissions? You might want to set `CONVOS_DEBUG=2` and see if you can gather something more information. Note however that the debug information is written to STDERR, and not to your log file.

My instance has about 600MB of log messages from back to 2016 and four users. I don't think we are in very heavy conversations though: The biggest log file for a month seems to be around 10MB.

**Comment by serhack** [comment] 2020-04-27 08:39
> Could it be an `ulimit` issue?
No, I do not think so. It shows me `unlimited` then I think it's fine. Nothing interesting neither in the syslog file. I set all the file both writable and readable by the user that runs Convos. I do not think there should be any problem in that side. I could try to open Convos as a root for a few minutes, but I do not think it's that problem.

> You might want to set CONVOS_DEBUG=2 and see if you can gather something more information. Note however that the debug information is written to STDERR, and not to your log file.

Oh, I thought `CONVOS_DEBUG` [was a boolean value](https://convos.by/doc/config.html#convos_debug). I'll try to run again Convos with that flag and then I'll update this issue. A note: I added the `CONVOS_LOG_FILE` so Convos can log all the warnings in a file.

 I mainly supposed it was caused by channels logs since I think there's something that goes in timeout.  I do not know if this is caused by low resources (e.g. RAM, CPU or disk space) but I do not think so since I monitor the resources and there's no warning.

**Comment by jhthorsen** [comment] 2020-04-27 08:50
`CONVOS_LOG_FILE` does not log "debug warnings" (such as the one produced by CONVOS_DEBUG), it only sends "normal" log messages to that file.

I don't think the issue is file permissions either, since it *should* show up in your regular log file.

Can you provide which modules are installed and the versions? You can get the information by running `./script/convos version`.

Also, can you check if this only happens for certain URLs or for all conversations? If so, could you provide the output from `du -sh $HOME/.local/share/convos/*/*/2020/*` ? I don't need the email, connection name, nor conversation name from that command - Just interested to see if you have *very large* conversation logs.

**Comment by serhack** [comment] 2020-04-27 09:06
Okay, I've understood what's happening. It appears that Convos tries to look for "future" channel logs (specifically it seems that wants to retrieve future logs in a period of one year). Those future logs naturally do not exist and then Convos end in an infinite loop. Molijous seems to kill the infinite loop causing an ERR:EMPTY_RESPONSE for that API call.

My suppositions were completely wrong.

Per each conversation, this happens:
`
[channel] No such file or directory: /rc-freenode/2021/04/channel.log
[channel] No such file or directory: /rc-freenode/2021/03/channel.log
[channel] No such file or directory: /rc-freenode/2021/02/channel.log
[channel] No such file or directory: /rc-freenode/2021/01/channel.log
[channel] No such file or directory: /rc-freenode/2020/12/channel.log
[channel] No such file or directory: /rc-freenode/2020/11/channel.log
[channel] No such file or directory: /rc-freenode/2020/10/channel.log
[channel] No such file or directory: /rc-freenode/2020/09/channel.log
[channel] No such file or directory: /rc-freenode/2020/08/channel.log
[channel] No such file or directory: /rc-freenode/2020/07/channel.log
[channel] No such file or directory: /rc-freenode/2020/06/channel.log
[channel] No such file or directory: /rc-freenode/2020/05/channel.log
`

> ./script/convos version

`CORE
  Convos                         4.03       (4.03)
  Perl                           v5.24.1    (5.16)
  Crypt::Eksblowfish             0.009      (0.009)
  File::HomeDir                  1.004      (1.00)
  File::ReadBackwards            1.05       (1.05)
  IO::Socket::SSL                2.067      (2.009)
  IRC::Utils                     0.12       (0.12)
  JSON::Validator                3.24       (3.24)
  LinkEmbedder                   1.12       (1.12)
  Mojolicious                    8.35       (8.35)
  Mojolicious::Plugin::OpenAPI   3.30       (3.30)
  Mojolicious::Plugin::Webpack   0.12       (0.12)
  Parse::IRC                     1.22       (1.22)
  Time::Piece                    1.31       (1.20)
  Unicode::UTF8                  0.62       (0.62)`

Logs were about 50 MB.

**Comment by serhack** [comment] 2020-04-28 09:15
I suspect the bug is [here](https://github.com/Nordaaker/convos/blob/master/lib/Convos/Core/Backend/File.pm). "before" or "after" variables are sent wrongly in my machine.

**Comment by jhthorsen** [comment] 2020-05-05 04:03
I *hope* this is fixed in "master" now. Will be part of the upcoming 4.04 release.

**Closed by jhthorsen** 2020-05-05 04:03 UTC
Labels: bug

**Comment by serhack** [comment] 2020-05-09 07:24
No, it's not fixed. I got the same log. :(

**Comment by jhthorsen** [comment] 2020-05-09 07:51
That is by design. Convos looks for log files 12 months back in time.

**Comment by serhack** [comment] 2020-05-09 08:01
@jhthorsen I understood that's by design. But I think it should not give error if the files are not retrieved.

**Comment by jhthorsen** [comment] 2020-05-09 08:05
Oh. That is indeed a bug. I forgot to add "...if DEBUG". Going to add that now.

**Comment by jhthorsen** [comment] 2020-05-09 08:11
Those messages are only visible if you set CONVOS_DEBUG=2 (or higher), so I don't understand how that is a problem.

Why do you call it an infinite loop, if it ends after ~12 iterations?

**Comment by serhack** [comment] 2020-05-09 08:14
> Why do you call it an infinite loop, if it ends after ~12 iterations?

Because those ~12 iterations are repeated for unlimited times. I just extracted the important logs.
