### ISSUE TITLE
Docker Container fails to build jQuery

### ISSUE THREAD

**Issue by almereyda** [Nordaaker/convos#234] opened 2014-12-28 23:46 UTC
When I'm building and running the container as in

```
git clone https://github.com/nordaaker/convos/convos.git
cd convos
docker build -t=nordaaker/convos:git .
docker run --name=convos -d -p 127.0.0.1:8080:8080
```

Firefox complains with

    SyntaxError: missing ; before statement c-3334b0c0c15a80e173f4cafe3603fa73.js:1
    ReferenceError: jQuery is not defined freenode:16

and Chrome for example with

    Uncaught SyntaxError: Unexpected identifier
    login:16 Uncaught ReferenceError: jQuery is not defined

**Comment by jhthorsen** [comment] 2015-01-02 11:46
This is fixed in 0.8603. The issue is that Mojolicious::Plugin::AssetPack fail to minify the new twitter API JavaScript.

**Closed by jhthorsen** 2015-01-02 11:46 UTC
