### ISSUE TITLE
Missing /LIST command

### ISSUE THREAD

**Issue by oliwer** [Nordaaker/convos#309] opened 2017-01-07 15:15 UTC
We should implement the /LIST IRC command to explore the available channels on a network.

Ideally, the list of channels returned by the server should be presented in a popup window, with the ability to sort the channels by the number of participants and to search by channel name and topic.

**Comment by jhthorsen** [comment] 2017-01-07 15:25
You can already get the list. It just looks pretty dull right now :(

Click on "Join dialog..." and then click on "LOAD DIALOGS".

**Comment by jhthorsen** [comment] 2017-01-07 15:28
Leaving this issue open, since I think the whole "Join dialog" dialog needs to be revamped. I'm considering loading the channel list without even prompting the user. What is holding me back, is that I'm not sure if the different networks like this. The good thing is that it's cached in convos, so it shouldn't really be an issue for the networks.

https://github.com/Nordaaker/convos/blob/master/lib/Convos/Core/Connection/Irc.pm#L164,L181

**Comment by oliwer** [comment] 2017-01-07 20:04
The LOAD DIALOGS button does not work for me. Nothings happens. Looking at the web console, i can see convos is sending an empty list : `{ rooms: [] }`

**Comment by jhthorsen** [comment] 2017-01-07 23:10
Which network is this?

**Comment by ekianjo** [comment] 2017-01-11 07:41
I can confirm that nothing happens here too on Freenode. And worse, this kind of dialog may actually crash the client in the way it's currently implemented (i had to restart convos after clicking it a few times since it did not react anymore).

**Comment by jhthorsen** [comment] 2017-01-11 08:46
@ekianjo: What do you mean about "crashing the client"? Do you have any log output or any other behaviour that can give more details regarding "crashing"?

I've already removed this feature in "master" now. Going to re-implement it by streaming the channel list over the websocket instead of doing a blocking API request.

**Comment by jhthorsen** [comment] 2017-01-29 00:05
This is now fixed in 0.99_24.

**Closed by jhthorsen** 2017-01-29 00:05 UTC
Labels: enhancement
