### ISSUE TITLE
Clicking on a notification element should take you to the correct place in the dialog

### ISSUE THREAD

**Issue by V3XATI0N** [Nordaaker/convos#330] opened 2017-04-10 18:35 UTC
It's great that Convos maintains a list of mentions in the notifications box, but it would be truly awesome if clicking on a notification not only activated the appropriate window as it does now, but auto-scrolled back in the chat buffer to the message contiaining the mention.

**Comment by jhthorsen** [comment] 2017-04-10 21:22
I totally agree. I'm not sure how to do that though. The issue is that let's say you click on a notification that came three days ago, should it load in all the messages for the last three days and then highlight the correct message? I think not... What I would like is to just load a small buffer (let's say 60 messages before and after the given message) and then allow you to scroll forward and backward in the stream of messages. But what happens if messages "right now" appears? Where should this message be placed, if you haven't scrolled to the end? Any input is more than welcome.

**Comment by V3XATI0N** [comment] 2017-04-10 21:33
I don't know how Convos tracks which messages are in the current buffer or how they fall off so I'm not exactly sure how to handle this question. If there's some method where Convos "knows" whether or not the notification relates to a message currently in the buffer, it could just scroll there, otherwise open a smaller 'history' buffer or something like you said with a range of posts before and after the mention. Maybe the notification box itself could be divided into "current" and "older" notifications using this same distinction to minimize user confusion over why some notifications behave differently from others.

Alternatively, clicking on an old notification could just cause the chat buffer to reload focused at the corresponding message (including some before and after range) and set up the 'infinite scroll' such that newer messages aren't loaded until you scroll back down. I'm not a dev so I don't know how trivial that is or isn't.

As for placement, maybe it would be simpler all around to embed the smaller buffer right inside the notification box, so for example each notification's div object contains an empty element that fills with the contents of the before/after messages when clicked, possibly along with a button for moving the focus to the main chat buffer which does load the entire conversation from the appropriate point onward (presumably that much effort on the user's part would indicate they are okay with whatever lag results from having to reload the main buffer).

**Comment by Wikiwide** [comment] 2019-05-30 02:16
Would be nice if clicking on floating (top right corner?) notification about a new message would:
1) take to correct tab in browser;
and
2) take to correct room/channel in Convos;
and
3) scroll to the correct place in conversation.

I am fairly sure that 2) doesn't happen currently?

**Comment by jhthorsen** [comment] 2019-10-27 05:38
I'm going to close this in favor of #187.

**Closed by jhthorsen** 2019-10-27 05:38 UTC
Labels: enhancement
