### ISSUE TITLE
idle time - disconnect

### ISSUE THREAD

**Issue by TimeRider07** [Nordaaker/convos#500] opened 2020-07-01 18:46 UTC
I was thinking if convos could have a "setting" where admin can set idle disconnect time period.

Example: If a user is idle for 12 hours then he would be disconnected from convos client. Then, after he log backs in his account, he would be automatically connected to IRC server or so.

It could actually save some CPU/memory uses? Also for users who would never login back or probably bots.

**Comment by jhthorsen** [comment] 2020-07-01 22:22
Going to close this as a duplicate of #499.

I won't save a whole lot of CPU/memory though, without a redesign of the backend.

**Closed by jhthorsen** 2020-07-01 22:22 UTC
Labels: duplicate
