### ISSUE TITLE
Can convos be used as open web client?

### ISSUE THREAD

**Issue by TimeRider07** [Nordaaker/convos#501] opened 2020-07-02 20:22 UTC
I was wondering if convos could be used as open client; where I mean it being used like mibbit client. (Public mode)
Like users can just put the username and enter.

So, having 2 modes; Public mode and which is now - private mode if I can say so), It could really attract people to use this client!

**Comment by jhthorsen** [comment] 2020-07-02 22:38
I think this is duplicate of #346 and maybe #499.

**Closed by jhthorsen** 2020-07-02 22:38 UTC
Labels: duplicate
